[project]
name = "my-app"
version = "0.1.0"
description = "My app"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "email@example.com"}
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    #"fastapi>=0.100.0",
    #"uvicorn[standard]>=0.23.0",
    #"sqlalchemy>=2.0.0",
    # "ipykernel>=6.29.5",
]

[dependency-groups]
dev = [    
    "mypy>=1.19.1",
    "ruff>=0.1.0",
    #"pytest>=7.0.0",
    #"httpx>=0.24.0",
]

[tool.ruff]
line-length = 88

select = [
    "E",   
    "W",   
    "F",  
    "I",   
    "UP",
]

exclude = [
    ".git",
    ".venv",
    "__pycache__",
]